config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  get "posts", to: "posts#new"

  post "posts", to: "posts#create"

  get "posts/:id", to: "posts#show", as: "show_post"

  get "posts/:id/edit", to: "posts#edit", as: "edit_post"

  patch "posts/:id/edit", to: "posts#update", as: "update_post"

  delete "posts/:id", to: "posts#destroy", as: "destroy_post"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.order(created_at: :desc)
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
    
        if @post.save
          redirect_to root_path, notice: 'Post was successfully created.'
        else
          render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to root_path
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to root_path, status: :see_other
    end
    
    private
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_blogpost.html.erb
<%= stylesheet_link_tag 'blogpost' %>

<div class="blog-post" >
    <button class="btn-delete" type="button"><%= link_to "Delete", destroy_post_path(post.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post?"} %></button>
    <button class="btn-edit" type="button"><%= link_to "Edit", edit_post_path(post.id) %></button>
    <h2><%= link_to post.title, show_post_path(post.id) %></h2>
    <p><%= post.body %></p>
    <p class="edit-info"> created: <%= post.created_at %></p>
    <p class="edit-info"> last updated: <%= post.updated_at %>,</p>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <%= link_to "nelerVar?", root_path, class: "navbar-link-left" %>
  <div class="navbar-links-right">
    <%= link_to "New Post", posts_path, class: "navbar-link-right"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NelerVar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Blog Entry</h1>

<%= form_with model: @post, data: { turbo: false }, method: :patch, url: update_post_path(@post) do |form| %>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </div>
    <div>
        <%= form.label :body%>
        <%= form.text_area :body, size: "150x10"%>
    </div>
    <%= form.submit "Edit post", class: "btn btn-primary" %>
<% end %>

app/views/posts/index.html.erb
<!-- app/views/posts/index.html.erb -->
<%= stylesheet_link_tag 'index' %>

<h1>Blog posts</h1>

<% @posts.each do |post| %>
    <%= render "layouts/blogpost", post: post %>
<% end %>

app/views/posts/new.html.erb
<h1>New Blog Entry</h1>

<%= stylesheet_link_tag 'newpost' %>

<%= form_with model: @post, data: { turbo: false } do |form| %>
    <div>
        <div>
            <%= form.label :title%>
        </div>
        <div>
            <%= form.text_field :title%>
        </div>
    </div>
    <div class="body">
        <div>
        <%= form.label :body%>
        </div>
        <div>
            <%= form.text_area :body, size: "150x10"%>
        </div>
    </div>

    <%= form.submit "Enter new post", class: "new-post-btn" %>
<% end %>

app/views/posts/show.html.erb
<%= render "layouts/blogpost", post: @post %>